---
sidebar: "year-2026"
---

## Event Details

- **Date:** April 18 - April 19
  - **Opening ceremony:** Saturday, April 18 10:00 am
  - **Presentations:** Sunday, April 19 12:00 pm
  - **Closing ceremony:** Sunday, April 19 1:30 pm
- **Location:** The Q-Center (MBH 202)
- **Prizes:** Prizes will be awarded for a variety of reasons, both technical and creative.

## Food schedule

Snacks will be provided throughout the day on Saturday according to the following schedule: 

- **10:00 am** - Assorted snacks, including Cookie Love cookies, vegetable platters, and more
- **2:30 pm** - Assorted sushi from Hero Sushi
- **7:00 pm** - Cake and more assorted snacks

## Volunteers

We are seeking volunteers to serve as judges or mentors for the event.

  - **Mentors** are present during the work hours to interact with groups and answer questions that arise. To be a mentor, no technical expertise is required. Mentors should feel empowered to offer technical advice if they so choose, but are primarily there to facilitate discussion among participants. 
  - **Judges** will watch presentations on Sunday and help award prizes; again, no technical expertise is required. 
  
If you are interested in participating as either a judge or mentor, please contact the Statistics faculty or sign up via the website below. 

***

For more details, please contact the Statistics faculty members ([stats@middlebury.edu](mailto:stats@middlebury.edu)).
